### ISSUE TITLE
The karabiner-ts npm package

### ISSUE THREAD

**Issue by evan-liu** [riccardoNovaglia/karabiner-ts-template#1]
Hi Riccardo, 

Thanks for putting your work on the karabiner config in TypeScript and make them open source and on npm. I have been thinking exactly the same thing and started [karabiner.ts](https://github.com/evan-liu/karabiner.ts) a few days ago. Only when I tried to publish to npm then I found that `karabiner-ts` already exists and I had to use `karabiner-config` instead. I noticed that your package is not actively worked on, and I plan to actively work on  [karabiner.ts](https://github.com/evan-liu/karabiner.ts) . So could you please have a look at  [karabiner.ts](https://github.com/evan-liu/karabiner.ts), and see if by any chance you'd like to use it for your config, and let it to have the `karabiner-ts` npm package name? Thanks for your time either way.

**Comment by riccardoNovaglia** [comment]
Hi Evan! Your project looks very neat!
You're right, I'm not particularly actively working on this project, I got it to the point where it can do everything I need it to, but don't necessarily plan on adding anything unless I need it or someone requests it.
Yes, happy to leave the name to yourself, I'm not particularly precious about it. I've just deleted it from npm, please go ahead and use it.
Likewise, thank you for your work! I also used to use Goku, but thought it would be much easier to use with TS. I'll definitely have a play with yours, I'm pretty sure it already supports everything mine did. If it doesn't I might open some PRs. Thanks for building it!

**Comment by evan-liu** [comment]
Thank you so much, Riccardo! I've changed the npm name. Please let me know if you have any feedback or feature requests for [karabiner.ts](https://github.com/evan-liu/karabiner.ts).
